### PR TITLE
Handle promise rejection in request recording

### LINKED ISSUE #120: Uncaught exception when canceling a request while sending body
## Observation

Mockttp throws the following uncaught exception when canceling a client HTTP request while sending body:

```
Error: Aborted
    at IncomingMessage.<anonymous> (/Users/p.dartus/code/_tmp/failed-post/node_modules/mockttp/dist/util/buffer-utils.js:63:40)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage._destroy (node:_http_incoming:224:10)
    at _destroy (node:internal/streams/destroy:109:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:71:5)
    at abortIncoming (node:_http_server:747:9)
    at socketOnClose (node:_http_server:741:3)
    at Socket.emit (node:events:525:35)
    at TCP.<anonymous> (node:net:313:12)
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
```

## Repro steps:

```js
import http from 'node:http';
import mockttp from 'mockttp';

const SERVER_PORT = 8080;
const PROXY_PORT = 8081;

const remote = mockttp.getLocal();

await remote.forAnyRequest().thenTimeout();
await remote.start(SERVER_PORT);

const server = mockttp.getLocal({
    debug: true
});

await server.forAnyRequest().thenPassThrough();
await server.start(PROXY_PORT);

const req = http.request({
    method: 'POST',
    host: 'localhost',
    path: `http://localhost:8080`,
    port: 8081,
    headers: {
        host: `localhost:8081`,
    },
});

req.write('Foo bar');

setTimeout(() => {
    req.on('error', () => {});
    req.destroy();
}, 1000);
```

## Version
- Node: `14`, `16`, `18`
- Mockttp: `3.6.1`

### PR DESCRIPTION
**Pull request by pmdartus**
This PR fixes #120, by handling the case where `waitForCompletedRequest` rejects when a request gets canceled in the middle of sending the request body.

With this change `getSeenRequests` would also return incomplete requests. For now, incomplete request bodies are empty, but ideally, incomplete requests bodies should return the data that has been received so far.

### CODE REVIEW

File: src/rules/requests/request-rule.ts [hunk 1]
```diff
@@ -82,6 +82,12 @@ export class RequestRule implements RequestRule {
                 ])
                 .catch(() => {}) // Ignore handler errors here - we're only tracking the request
                 .then(() => waitForCompletedRequest(req))
+                .catch(() => {
+                    // If for some reason the request is not completed, we still want to record it.
+                    // TODO: Update the body to return the data that has been received so far.
+                    const completedRequest = buildInitiatedRequest(req);
+                    return {...completedRequest, body: buildBodyReader(Buffer.from([]), req.headers) };
```
Comment (pmdartus) [inline src/rules/requests/request-rule.ts:89]: I haven't found yet an elegant way to create a body ready, at this stage, with the data that has been transmitted so far. For now, I created an empty body to solve the promise rejection issue. But it's certainly something that should be improved in the future.

Comment (pimterry) [reply src/rules/requests/request-rule.ts]: Yep, that's fair. I'm not too worried about it to be honest, since it's an unusual edge case and I'm not sure it's worth the complexity, but yes leaving the TODO to look at that in future is fine.
